Sales Illustration/Models/NasabahData.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sales.Illustration.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NasabahData
    {
        public long NasabahDataId { get; set; }
        public string TransCode { get; set; }
        public string PolicyHolderName { get; set; }
        public Nullable<System.DateTime> PolicyHolderDOB { get; set; }
        public string PolicyHolderGender { get; set; }
        public Nullable<int> PolicyHolderRiskClassId { get; set; }
        public Nullable<int> PolicyHolderAge { get; set; }
        public Nullable<bool> IsMainInsured { get; set; }
        public string InsuredName { get; set; }
        public Nullable<System.DateTime> InsuredDOB { get; set; }
        public string InsuredGender { get; set; }
        public Nullable<int> InsuredRiskClassId { get; set; }
        public Nullable<int> InsuredAge { get; set; }
        public string Relation { get; set; }
        public string ChildName { get; set; }
        public Nullable<System.DateTime> ChildDOB { get; set; }
        public string ChildGender { get; set; }
        public Nullable<int> ChildAge { get; set; }
        public string ProductCode { get; set; }
        public string Language { get; set; }
    
        public virtual TransLog TransLog { get; set; }
    }
}

Sales Illustration/Models/RiderType.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sales.Illustration.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiderType
    {
        public RiderType()
        {
            this.RiderProducts = new HashSet<RiderProduct>();
            this.RiderRates = new HashSet<RiderRate>();
        }
    
        public int RiderTypeId { get; set; }
        public string RiderCode { get; set; }
        public string TypeName { get; set; }
        public Nullable<int> MinAge { get; set; }
        public Nullable<int> MaxAge { get; set; }
        public Nullable<int> CoverTerm { get; set; }
        public Nullable<int> ParentRiderType { get; set; }
        public string Description { get; set; }
        public string DescriptionEN { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Rider Rider { get; set; }
        public virtual ICollection<RiderProduct> RiderProducts { get; set; }
        public virtual ICollection<RiderRate> RiderRates { get; set; }
    }
}

Sales Illustration/Controllers/ReportController.cs
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;
using Sales.Illustration.Web.Extensions;
using Sales.Illustration.Web.Helper;
using Sales.Illustration.Web.Services;
using Sales.Illustration.Web.ViewModel;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Net.Security;
using System.Security.Cryptography.X509Certificates;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Sales.Illustration.Web.Controllers
{
    public class ReportController : Controller
    {
        //
        // GET: /Report/

        public ActionResult Index()
        {
            return View();
        }

        [DeleteFile]
        public virtual FileResult Download()
        {
            var fullPath = Path.Combine(Server.MapPath("~/Report/temp"), _session.TransLogCode + ".pdf");
            var fi = new FileInfo(fullPath);

            return fi.Exists ? File(fullPath, System.Net.Mime.MediaTypeNames.Application.Octet, Path.GetFileName(fullPath)) : File(fullPath, System.Net.Mime.MediaTypeNames.Application.Octet, Path.GetFileName(RegenerateReport()));
        }

        [DeleteFile]
        public async Task<ActionResult> SendMail(SendMailViewModel model)
        {
            var message = new MailMessage();
            message.To.Add(new MailAddress(model.To));
            message.From = new MailAddress("sis@hanwha.co.id");
            message.Subject = model.Subject;
            message.Body = model.Body;
            message.IsBodyHtml = true;

            var fullPath = Path.Combine(Server.MapPath("~/Report/temp"), _session.TransLogCode + ".pdf");
            var fi = new FileInfo(fullPath);

            if (fi.Exists)
            {
                message.Attachments.Add(new Attachment(fullPath));
            }
            else
            {
                var path = RegenerateReport();
                message.Attachments.Add(new Attachment(path));
            }

            using (var smtp = new SmtpClient())
            {

                var email = ConfigurationManager.AppSettings["Email"];
                var password = ConfigurationManager.AppSettings["Password"];
                var host = ConfigurationManager.AppSettings["SMTP"];

                var credential = new NetworkCredential
                {
                    UserName = email,
                    Password = password
                };

                smtp.Credentials = credential;
                smtp.Host = host;
                smtp.Port = 587;
                smtp.UseDefaultCredentials = false;
                smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
                smtp.EnableSsl = true;

                await smtp.SendMailAsync(message);
                message.Attachments.Dispose();

                if (model.Source.Equals("tra"))
                    return RedirectToAction("ResetAllData", "Traditional");
                else
                    return RedirectToAction("ResetAllData", "UnitLink");
            }
        }

        private string RegenerateReport()
        {
            SummaryViewModel dataInput = new SummaryViewModel();
            dataInput.Nasabah = _session.dataNasabah;
            dataInput.Premi = _session.premiInvestmentData;
            dataInput.Rider = _session.riderData;
            dataInput.Additional = _session.addInsData;
            dataInput.TopUp = _session.topUpWithData;
            dataInput.Insurance = _session.insCostRatioData;

            if (_session.addInsData != null)
                dataInput.Additional = _session.addInsData;
            else
                dataInput.Additional = new AdditionalInsuredViewModel();

            Thread.CurrentThread.CurrentUICulture = CultureInfo.GetCultureInfo(dataInput.Insurance.Language);

            var result = MainServices.GenerateReport(dataInput, _session.AgentName, _session.AgentCode, _session.AppVersion);

            var rptH = new ReportDocument { FileName = Server.MapPath(string.Format("~/Report/{0}.rpt", result.ReportName)) };
            rptH.SetDataSource(result.IllustrationDataSet);

            var guid = _session.TransLogCode + ".pdf";
            var path = Path.Combine(Server.MapPath("~/Report/temp"), guid);
            rptH.ExportToDisk(ExportFormatType.PortableDocFormat, path);

            return path;
        }
    }
}

Sales Illustration/Controllers/TraditionalController.cs
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;
using Sales.Illustration.Web.Domain;
using Sales.Illustration.Web.Extensions;
using Sales.Illustration.Web.Helper;
using Sales.Illustration.Web.Services;
using Sales.Illustration.Web.ViewModel;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace Sales.Illustration.Web.Controllers
{
    [SessionExpire]
    public class TraditionalController : Controller
    {
        Sales.Illustration.Web.Models.MainModel obj = new Sales.Illustration.Web.Models.MainModel();

        //
        // GET: /Traditional/

        public ActionResult Index()
        {
            _session.dataNasabah = null;
            _session.premiInvestmentData = null;
            _session.riderData = null;
            _session.insCostRatioData = null;
            _session.TransLogCode = null;

            return RedirectToAction("NasabahData");
        }

        public ActionResult NasabahData()
        {
            var model = new NasabahDataViewModel();

            if (_session.dataNasabah != null)
                model = _session.dataNasabah;

            ViewData["riskClass"] = obj.GetActiveRiskClass().Select(x => new SelectListItem { Text = x.RiskClassDesc, Value = x.RiskClassId.ToString() });
            ViewData["products"] = obj.GetProductByType("tra").Select(x => new SelectListItem { Text = x.ProductName, Value = x.ProductCode });

            return View("NasabahData", model);
        }

        [HttpPost]
        public ActionResult ValidateNasabahData(NasabahDataViewModel data)
        {
            if (data.TertanggungUtama == "Ya")
            {
                data.NamaTertanggungUtama = null;
                data.JenisKelaminTertanggungUtama = null;
                data.TanggalLahirTertanggungUtama = null;
                data.StatusPekerjaanTertanggungUtama = null;
                data.KelasPekerjaanTertanggungUtama = null;
                data.UmurTertanggungUtama = null;
                data.Relation = null;
            }

            _session.dataNasabah = data;

            return RedirectToAction("PremiumAndInvestment");
        }

        public ActionResult BackToNasabahData()
        {
            if (_session.premiInvestmentData != null)
                _session.premiInvestmentData = null;

            return RedirectToAction("NasabahData");
        }

        public ActionResult PremiumAndInvestment()
        {
            var model = new PremiumAndInvestmentViewModel();

            if (_session.premiInvestmentData != null)
                model = _session.premiInvestmentData;

            var insAge = 0;
            if (_session.dataNasabah.TertanggungUtama == "Ya")
                insAge = Convert.ToInt32(_session.dataNasabah.UmurPemegangPolis);
            else
                insAge = Convert.ToInt32(_session.dataNasabah.UmurTertanggungUtama);

            ViewData["insAge"] = insAge;
            model.UsiaMasukAnak = _session.dataNasabah.UmurAnak;
            ViewData["paymentMethods"] = obj.GetActivePaymentMethod().Select(x => new SelectListItem { Text = x.PMName, Value = x.PMCode.ToString() });
            var product = obj.GetProduct(_session.dataNasabah.NamaProduk);
            ViewData["ProductTitle"] = product.ProductName;

            return View("PremiumAndInvestment", model);
        }

        [HttpPost]
        public ActionResult ValidatePremiumAndInvestmentData(PremiumAndInvestmentViewModel data)
        {
            _session.premiInvestmentData = data;

            return RedirectToAction("Rider");
        }

        public ActionResult BackToPremiumAndInvestment()
        {
            if (_session.riderData != null)
                _session.riderData = null;

            if (_session.addInsData != null)
                _session.addInsData = null;

            return RedirectToAction("PremiumAndInvestment");
        }

        public ActionResult Rider()
        {
            var model = new RiderViewModel();

            if (_session.riderData != null)
            {
                model = _session.riderData;
            }
            else
            {
                var riders = obj.GetRiderByProduct(_session.dataNasabah.NamaProduk).GroupBy(x => x.RiderCode).Select(x => x.First());
                model.Riders = new List<Domain.RiderItem>();
                var totalBiayaAsuransi = 0;

                foreach (var rider in riders)
                {
                    List<Choices> choices = new List<Choices>();
                    var prod = obj.GetProduct(_session.dataNasabah.NamaProduk);

                    var check = prod.ProductCategory.Equals("wizer") && (rider.RiderCode == "WOP" || rider.RiderCode == "ADB");
                    var uangPertanggungan = prod.ProductCategory.Equals("wizer") && (rider.RiderCode == "ADB") ? 3 * Int32.Parse(_session.premiInvestmentData.UangPertanggungan.Replace(",", "")) : 0;
                    var allocationPercent = prod.ProductCategory.Equals("wizer") && (rider.RiderCode == "ADB") ? "300%" : "0%";
                    var biayaAsuransi = prod.ProductCategory.Equals("wizer") && (rider.RiderCode == "ADB") ?
                        (int)MainServices.CalculateCostOfRider(new SummaryViewModel(), uangPertanggungan, rider.RiderCode,
                        null, _session.dataNasabah.UmurPemegangPolis, Int32.Parse(_session.dataNasabah.KelasPekerjaanPemegangPolis), rider.Category, prod, null) : 0;

                    var riderTypeList = obj.GetRiderProduct(prod.ProductCode, rider.RiderCode).Where(x => x.RiderTypeId != null).Select(x => x.RiderTypeId).ToList();

                    foreach (var c in rider.RiderTypes.Where(x => riderTypeList.Contains(x.RiderTypeId)))
                    {
                        var choice = new Choices();
                        choice.Checked = c.TypeName == "CI" && prod.ProductCategory.Equals("wizer");
                        choice.RiderType = c;

                        uangPertanggungan = choice.Checked ? Int32.Parse(_session.premiInvestmentData.UangPertanggungan.Replace(",", "")) : 0;
                        var dataInput = new SummaryViewModel();
                        var riderCode = rider.RiderCode;
                        var riderType = c.RiderTypeId;
                        var age1 = _session.dataNasabah.UmurPemegangPolis;
                        var riderCategory = rider.Category;
                        biayaAsuransi += choice.Checked ? (int)MainServices.CalculateCostOfRider(dataInput, uangPertanggungan, riderCode, riderType, age1, null, riderCategory, prod, null) : 0;

                        choices.Add(choice);
                    }

                    totalBiayaAsuransi += biayaAsuransi;
                    model.Riders.Add(new Domain.RiderItem() { Rider = rider, Checked = check, Choices = choices, BiayaAsuransi = string.Format("{0:n0}", biayaAsuransi).Replace(".", ","), UangPertanggungan = uangPertanggungan > 0 ? string.Format("{0:n0}", uangPertanggungan).Replace(".", ",") : "", AllocationPercent = allocationPercent });
                }

                model.BiayaAsuransiTambahan = string.Format("{0:n0}", totalBiayaAsuransi);
            }

            var insAge = 0;
            if (_session.dataNasabah.TertanggungUtama == "Ya")
                insAge = Convert.ToInt32(_session.dataNasabah.UmurPemegangPolis);
            else
                insAge = Convert.ToInt32(_session.dataNasabah.UmurTertanggungUtama);

            ViewData["up"] = _session.premiInvestmentData.UangPertanggungan;
            ViewData["ttgUtama"] = _session.dataNasabah.TertanggungUtama;
            ViewData["modebayar"] = _session.premiInvestmentData.ModeBayarPremi;
            ViewData["masaasuransi"] = _session.premiInvestmentData.MasaAsuransi;
            ViewData["masabayar"] = _session.premiInvestmentData.RencanaMasaPembayaran;
            ViewData["carabayar"] = _session.premiInvestmentData.CaraBayar;
            ViewData["insage"] = insAge;
            var product = obj.GetProduct(_session.dataNasabah.NamaProduk);
            ViewData["ProductTitle"] = product.ProductName;

            model.NasabahData = _session.dataNasabah;

            return View("Rider", model);
        }

        [HttpPost]
        public ActionResult ValidateRiderData(RiderViewModel data)
        {
            _session.riderData = data;

            return RedirectToAction("InsuranceCostAndRatio");
        }

        public ActionResult BackToRider()
        {
            if (_session.insCostRatioData != null)
                _session.insCostRatioData = null;

            return RedirectToAction("Rider");
        }

        public ActionResult InsuranceCostAndRatio()
        {
            var model = new InsuranceCostAndRatioViewModel();

            if (_session.insCostRatioData != null)
                model = _session.insCostRatioData;

            if (_session.riderData.BiayaAsuransiTambahan != null)
                model.BiayaAsuransiTambahan = _session.riderData.BiayaAsuransiTambahan;
            else
                model.BiayaAsuransiTambahan = "0";

            ViewData["language"] = obj.GetActiveLanguage().Select(x => new SelectListItem { Text = x.Name, Value = x.CultureId });
            model.Premi = _session.premiInvestmentData.PremiBerkala;
            var product = obj.GetProduct(_session.dataNasabah.NamaProduk);
            ViewData["ProductTitle"] = product.ProductName;

            return View("InsuranceCostAndRatio", model);
        }

        [HttpPost]
        public ActionResult ValidateInsuranceCostAndRatioData(InsuranceCostAndRatioViewModel data)
        {
            _session.insCostRatioData = data;

            return RedirectToAction("Summary");
        }

        public ActionResult Summary()
        {
            var model = new SummaryViewModel();

            if (_session.dataNasabah != null)

Sales Illustration/Views/Traditional/InsuranceCostAndRatio.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var pTitle = ViewData["ProductTitle"];
}
@model Sales.Illustration.Web.ViewModel.InsuranceCostAndRatioViewModel

@Html.Partial("Header")
<div id="wrapper" ng-app="myApp" ng-controller="myCtrl">
    @Html.Partial("SideBar")
    <div class="main-tittle">
        <center><h5 class="main-tittle"><b>@pTitle</b></h5></center>
    </div>
    <div style="min-height:40px;overflow:hidden;">
        <center>
            <div id="msform">
                <ul id="progressbar" style="padding-left:0px;">
                    <li class="active"></li>
                    <li class="active"></li>
                    <li class="active"></li>
                    <li class="active"></li>
                </ul>
            </div>
        </center>
    </div>

    <div class="main-content">
        <div class="row">
            <div class="col-lg-12">
                @using (Html.BeginForm("ValidateInsuranceCostAndRatioData", "Traditional", FormMethod.Post, new { @id = "form" }))
                {
                    <div class="content-tittle-1">
                        <img src="/Content/dist/img/icon-cost.png" /> Premi Asuransi & Pilihan Bahasa
                    </div>
                    <fieldset>
                        <div class="col-lg-12">
                            <div class="row row-form" style="margin:0px -30px;">
                                <div class="col-lg-10 col-md-10 col-sm-11 col-xs-12 jarak">
                                    <div class="col-lg-5 col-md-5 col-sm-5 col-xs-12">
                                        <label class="control-label">
                                            Premi Asuransi Dasar
                                        </label>
                                    </div>
                                    <div class="col-lg-5 col-md-5 col-sm-5 col-xs-12">
                                        @Html.TextBoxFor(m => m.Premi, new { @class = "form-control", @readonly = "readonly" })
                                    </div>
                                </div>
                                <div class="col-lg-10 col-md-10 col-sm-11 col-xs-12 jarak">
                                    <div class="col-lg-5 col-md-5 col-sm-5 col-xs-12">
                                        <label class="control-label">
                                            Premi Asuransi Tambahan
                                        </label>
                                    </div>
                                    <div class="col-lg-5 col-md-5 col-sm-5 col-xs-12">
                                        @Html.TextBoxFor(m => m.BiayaAsuransiTambahan, new { @class = "form-control", @readonly = "readonly" })
                                    </div>
                                </div>
                                <div class="col-lg-10 col-md-10 col-sm-11 col-xs-12 jarak">
                                    <div class="col-lg-5 col-md-5 col-sm-5 col-xs-12">
                                        <label class="control-label">
                                            Total Premi
                                        </label>
                                    </div>
                                    <div class="col-lg-5 col-md-5 col-sm-5 col-xs-12">
                                        @Html.TextBoxFor(m => m.BiayaAsuransiTotal, new { @class = "form-control", @readonly = "readonly" })
                                    </div>
                                </div>
                                <div class="col-lg-10 col-md-10 col-sm-11 col-xs-12 jarak">
                                    <div class="col-lg-5 col-md-5 col-sm-5 col-xs-12">
                                        <label class="control-label">
                                            Pilihan Bahasa
                                        </label>
                                    </div>
                                    <div class="col-lg-5 col-md-5 col-sm-5 col-xs-12">
                                        @Html.DropDownListFor(m => m.Language, ViewData["language"] as IEnumerable<SelectListItem>, new { @class = "form-control" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                }
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 navigationbutton">
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                <button id="content_save" class="btn btn-warning" onclick="window.location.href='@Url.Action("BackToRider", "Traditional")';">
                    BACK
                </button>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 btn-bawah-mid">
                <button id="content_clear" class="btn btn-warning" onclick="window.location.href='@Url.Action("ClearTraditionalInsuranceCostAndRatioData", "ClearData")';">
                    CLEAR
                </button>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 btn-bawah-right">
                <button class="btn btn-warning" onclick="next()">
                    NEXT
                </button>
            </div>
        </div>
    </div>

</div>
@Html.Partial("Footer")
@System.Web.Optimization.Scripts.Render("~/bundles/app")

<script type="text/javascript">
    $(document).ready(function () {
        var x = $('#@Html.IdFor(m => m.Premi)').val();
        var y = $('#@Html.IdFor(m => m.BiayaAsuransiTambahan)').val();

        $('#@Html.IdFor(m => m.BiayaAsuransiTotal)').val(toMoneyFormat(parseInt(toDecimalFormat(x)) + parseInt(toDecimalFormat(y))));
    });

    function next() {
        $("#form").submit();
    }
</script>

Sales Illustration/Views/Traditional/Report.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    string errorMsg = TempData["errorMsg"] != null ? TempData["errorMsg"].ToString() : "";
    string path = ViewData["path"].ToString().Replace("\\", "/");
    var pTitle = ViewData["ProductTitle"];
}

@Html.Partial("Header")
<div id="wrapper" ng-app="myApp" ng-controller="myCtrl">
    @Html.Partial("SideBar")
    <div class="main-tittle">
        <center><h5 class="main-tittle"><b>@pTitle</b></h5></center>
    </div>

    <div class="main-content" style="padding: 0px;">
        <div class="row">
            <div class="col-lg-12">
                <iframe width="100%" height="100%" src="@path"></iframe>
                <input type="hidden" id="hdErrorMsg" value="@errorMsg" />
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 navigationbutton">
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                <button id="content_save" class="btn btn-warning" onclick="window.location.href='@Url.Action("ResetAllData", "Traditional")';">
                    CREATE NEW
                </button>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 btn-bawah-mid">
                <button id="content_save" class="btn btn-warning" onclick="window.location.href='@Url.Action("Download", "Report")';">
                    SAVE PDF
                </button>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 btn-bawah-right">
                <button id="content_save" class="btn btn-warning" onclick="window.location.href='@Url.Action("SendMailReport", "Traditional")';">
                    EMAIL
                </button>
            </div>
        </div>
    </div>

</div>
@Html.Partial("Footer")

<script type="text/javascript">
    $(document).ready(function () {
        var msg = $('#hdErrorMsg').val();

        if (msg != null && msg != "") {
            alertify.alert(msg);
        }
    });
</script>

Sales Illustration/Views/Traditional/SendMailReport.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var pTitle = ViewData["productName"];
    var subject = ViewData["subject"];
    var attachment = ViewData["attachment"];
}
@model Sales.Illustration.Web.ViewModel.SendMailViewModel

@Html.Partial("Header")
<div id="wrapper" ng-app="myApp" ng-controller="myCtrl">
    @Html.Partial("SideBar")
    <div class="main-tittle">
        <center><h5 class="main-tittle"><b>@pTitle</b></h5></center>
    </div>

    <div class="main-content" style="padding: 0px;">
        <div class="row">
            <div class="col-lg-12">
                <div class="content-tittle-1">
                    <i class=""></i> Send Mail Report
                </div>
                @using (Html.BeginForm("SendMail", "Report", FormMethod.Post, new { @id = "form" }))
                {
                    <fieldset>
                        <div class="col-lg-12">
                            <div class="row row-form" style="margin:0px -30px;">
                                <div class="col-lg-10 col-md-10 col-sm-11 col-xs-12 jarak">
                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                        <label class="control-label">
                                            To
                                        </label>
                                    </div>
                                    <div class="col-lg-8 col=-md-8 col-sm-8 col-xs-12">
                                        @Html.TextBoxFor(m => m.To, new { @class = "form-control", @placeholder = "Mail To" })
                                    </div>
                                </div>
                                <div class="col-lg-10 col-md-10 col-sm-11 col-xs-12 jarak">
                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                        <label class="control-label">
                                            Subject
                                        </label>
                                    </div>
                                    <div class="col-lg-8 col=-md-8 col-sm-8 col-xs-12">
                                        @Html.TextBoxFor(m => m.Subject, new { @class = "form-control", @readonly = "readonly" })
                                    </div>
                                </div>
                                <div class="col-lg-10 col-md-10 col-sm-11 col-xs-12 jarak">
                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                        <label class="control-label">
                                            Attachment
                                        </label>
                                    </div>
                                    <div class="col-lg-8 col=-md-8 col-sm-8 col-xs-12">
                                        @Html.TextBoxFor(m => m.Attachment, new { @class = "form-control", @readonly = "readonly" })
                                    </div>
                                </div>
                                <div class="col-lg-10 col-md-10 col-sm-11 col-xs-12 jarak">
                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                        <label class="control-label">
                                            Body
                                        </label>
                                    </div>
                                    <div class="col-lg-8 col=-md-8 col-sm-8 col-xs-12">
                                        @Html.TextAreaFor(m => m.Body, new { @class = "form-control" })
                                        @Html.HiddenFor(m => m.Source)
                                    </div>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                }
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 navigationbutton">
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                <button id="content_save" class="btn btn-warning" onclick="window.location.href='@Url.Action("ResetAllData", "Traditional")';">
                    CREATE NEW
                </button>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 btn-bawah-mid">
                <button class="btn btn-warning" onclick="next()">
                    SEND MAIL
                </button>
            </div>
        </div>
    </div>

</div>
@Html.Partial("Footer")

<script type="text/javascript">
    function next() {
        $("#form").submit();
    }
</script>